name: on-main

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - sheduler
    types:
      - completed

jobs:
  on-main:
    runs-on: ubuntu-latest
    steps:
      - run: echo work
