name: scheduler

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gen file
        run: echo $RANDOM > file
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'feat(upstream): auto sync remixicon version'
          add: file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
